---
dependencies: []

galaxy_info:
  role_name: dotfiles
  author: Nathan Dentzau
  description: Install dotfiles, SSH keys, NVM, and Oh My Zsh for a user.
  license: "MIT"
  min_ansible_version: 2.15.1
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - dotfiles
    - development
    - nvm
    - oh-my-zsh
    - ssh
    - zsh
    - local
    - user

