---
- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_facts.distribution}}.yml'
        - '{{ansible_facts.os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- include_tasks: setup-Debian.yml
  when: ansible_facts.os_family == 'Debian'

- name: Install DDEV package.
  ansible.builtin.package:
    name: ddev
    state: "{{ ddev_package_state }}"
  when: ansible_facts.os_family == 'Debian'

- name: Install mkcert local CA.
  ansible.builtin.command: mkcert -install
  when: ddev_install_mkcert | bool
  ignore_errors: true
  changed_when: false
  failed_when: false

