---
dependencies:
  - geerlingguy.docker

galaxy_info:
  role_name: ddev
  author: Nathan Dentzau
  description: Install DDEV (Docker-based local development environment).
  license: "MIT"
  min_ansible_version: 2.15.1
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble
  galaxy_tags:
    - web
    - development
    - docker
    - ddev
    - local
    - server

